### ISSUE TITLE
本番環境サーバへのデプロイをちょっと楽にしたい…したくない？

### ISSUE THREAD

**Issue by kuroma6666** [NamagomiNetwork/Namagomi-bot#121]
Ownerの@ikazuchizero が`g!shell git pull origin main`を打ってリモートリポジトリのmainブランチの最新を本番環境にデプロイしてもらっているけど、毎回タイプするのはダルそうってのと過去にタイプミスで1回事故っていることを踏まえて短縮コマンド（別名登録したエイリアスコマンドみたいなもん）を作りたい。

当然だが管理者向けコマンドでの実装予定

コマンド名の案：
- deploy
- ploh(pull origin HEADの略)
- pull

**Comment by kuroma6666** [comment]
半自動ではなくて楽にしようとしてる内容だったのでタイトル修正

**Comment by ikazuchizero** [comment]
全自動git pull origin main

**Comment by ikazuchizero** [comment]
g!t pull origin main

**Comment by kuroma6666** [comment]
g!プリフィクスに合わせた「t pull origin main」コマンド実装しちゃうか？

**Comment by ikazuchizero** [comment]
半角スペースで全てが崩壊する未来が見える

**Comment by kuroma6666** [comment]
半角スペース含んだコマンドなんて正気のSATAではないな、deployみたいなのが安牌かもしれん

**Comment by ikazuchizero** [comment]
g!なんちゃらでできそうな文字列を探したい所存

**Comment by kuroma6666** [comment]
一旦deployコマンドを作ってみようかしら。。

**Comment by kuroma6666** [comment]
これやるか
