### ISSUE TITLE
変数の再宣言をつぶせ

### ISSUE THREAD

**Issue by nabr2730** [NamagomiNetwork/Namagomi-bot#27]
はい....

**Comment by kuroma6666** [comment]
変数の再宣言に引っかかっている(と思われる)所
`/commands`：
- omikuji.js
- 該当変数：random,unique,result

`/events`：
- messageCreate.js
- 該当変数：prefix

`/sub-systems`
- kagawa-notification.js
- 該当変数：embed

その他備考：
ESLintを導入し`no-redeclare`ルールを頑張って適用すると再宣言されている箇所について確認できる
https://eslint.org/docs/latest/rules/no-redeclare

**Comment by kuroma6666** [comment]
関連 #117 
今は多分再宣言がないと思うんだけど、`no-redeclare`をerrorにするルール追加してあげればIssue Closeしてよさそう
https://github.com/NamagomiNetwork/Namagomi-bot/blob/main/.eslintrc.json
