### ISSUE TITLE
randomコマンドの試行回数指定について引数が数字かどうかチェックする

### ISSUE THREAD

**Issue by kuroma6666** [NamagomiNetwork/Namagomi-bot#49]
## 現状
- 引数指定で単一文字/文字列を受け付けてしまい、試行回数として表現される
→抽選結果は何も出力しない
→試行回数の表示が`{文字列}/{数字}`になってしまう
- randomコマンド実行例：`g!random a h o g e h o g e`

## 期待
- 試行回数を指定する引数については数字かどうかのチェックをする
- チェックをすることで試行回数に文字列を渡さない
- 文字列を渡してしまった場合に数字を指定するように促す引数チェックエラー文を出力する
- 浮動小数点を通さず、整数のみの入力制限にする
## 備考
- 試行回数指定について、数値リテラルなら実は何でも通る
- 整数(2進数、8進数、10進数、16進数)、浮動小数点も通るし抽選結果は出てくる
- わざわざ試行回数を2/8/16進で表現するユースケースを考えにくい
- 10進数に制限する必要は無いので柔軟な仕様にしておいてもよい
- 2進数(8=0b1000)を試行回数指定した実行例：`g!random 0b1000 h o g e h o g e`

**Comment by yuuki1293** [comment]
randomコマンドで少数を入力した時に切り上げになるのは直感に反するので、整数に制限するか切り捨てした方がいい。

**Comment by kuroma6666** [comment]
小数が切り上げになるのはたしかに直感に反しますね。(指定回数例：1.1→2)
整数のみの入力制限に倒そうと思います。
